global:
  scrape_interval: "15s"     # By default, scrape targets every 15 seconds.
  evaluation_interval: "15s" # By default, evaluate rules every 15 seconds.

rule_files:
  - "synapse.rules"

scrape_configs:
  - job_name: "synapse"
    metrics_path: "/_synapse/metrics"
    target_groups:
      - targets:
          - "localhost:8008"

